---
title: "Airport Departure Delays: Part 1"
author: "Jules Gdovic"
date: "06/13/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### The data and graph show that departure delays vary upon specific airport and weekday.

```{r}
library(tidyverse)
library(nycflights13)
library(knitr)
library(ggplot2)
library(plotrix)
library(lubridate)
```

```{r}
flites_dest_names <- flights%>%
  inner_join(airports, by = c("dest" = "faa")) %>%
  rename(dest_airport=name)
```

```{r}
flites_day <- flites_dest_names %>%
  mutate(weekday = wday(time_hour))
```

```{r}
flites_per_weekday <- flites_day %>%
  group_by(weekday) %>%
  summarize(number_of_flights = n())
```


```{r}
flites_day$weekday <- factor(flites_day$weekday,
                             labels = c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday",
                                        "Friday", "Saturday"))
```


```{r}
summary_dep_delay <- flites_day %>%
  group_by(origin, weekday) %>%
  summarize(mean = mean(dep_delay, na.rm = TRUE),
            std_dev = sd(dep_delay, na.rm = TRUE),
            std_err = std.error(dep_delay, na.rm = TRUE))
```

## Departure Delays
```{r}
kable(summary_dep_delay)
```

## Departure Delays Graph
```{r}
ggplot(summary_dep_delay, aes(x=weekday, y=mean, fill=origin)) +
  geom_bar(position = "dodge", stat = "identity", color = "black") +
  scale_fill_manual(name="Airport", values = c("grey40", "grey65", "grey100")) +
  geom_errorbar(aes(ymax=mean+std_err, ymin=mean-std_err), width=.1,
                position = position_dodge(.9)) +
  labs(y="Mean Departure Delay (min)")
```



